name: Deploy

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: snippet-war

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest ./backend

      - name: Save image to tar
        run: |
          docker save -o ${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:latest

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-docker-image
          path: ${{ env.IMAGE_NAME }}.tar

  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Download docker-image artefact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-docker-image
          path: .

      - name: Upload image to server vis scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ env.IMAGE_NAME }}.tar
          target: /tmp

      - name: Deploy image to server via ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load -i /tmp/${{ env.IMAGE_NAME }}.tar

            docker stop ${{ env.IMAGE_NAME }}-container
            docker rm ${{ env.IMAGE_NAME }}-container

            docker run -d \
              --name ${{ env.IMAGE_NAME }}-container \
              -p 8081:8081 \
              -e OPENROUTER_API_KEY="${{ secrets.OPENROUTER_API_KEY }}" \ 
              -e OPENROUTER_MODEL=deepseek/deepseek-chat \ 
              -e OPENROUTER_BASE_URL=https://openrouter.ai/api/v1 \ 
              -e OPENROUTER_TIMEOUT=30s \ 
              -e OPENROUTER_MAX_TOKENS=2000 \ 
              -e PROXYAPI_BASE_URL=https://api.proxyapi.ru/openai/v1 \ 
              -e PROXYAPI_TIMEOUT=30s \ 
              -e PROXYAPI_MAX_TOKENS=2000 \ 
              -e PROXYAPI_MODEL=gpt-4.1-mini \ 
              -e PROXYAPI_API_KEY="${{ secrets.PROXYAPI_API_KEY }}" \
              ${{ env.IMAGE_NAME }}:latest

            docker image prune -f